// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JD.iPhone
{
	public partial class SearchCell : UITableViewCell
	{
		public SearchCell (IntPtr handle) : base (handle)
		{
		}
	}
}
